# agents:
#   queue: kubernetes

steps:
- label: ":white_check_mark: Successful Step"
  command: "echo 'This step will pass successfully'"

- label: ":x: Command Failure Only (Logic)"
  command: echo "exit 2"

- label: ":warning: Soft Fail (Does Not Block Pipeline)"
  command: echo "exit 5"
  soft_fail: true

- label: ":bookmark: Set Release Version Metadata"
  command: "buildkite-agent meta-data set 'release-version' '1.0.0'"

- label: ":mag: Get and Print Release Version Metadata"
  command: "echo 'Release Version: $$(buildkite-agent meta-data get release-version)'"

- label: ":rocket: Final Step (Always Runs)"
  command: "echo 'Pipeline has completed!'"
