# agents:
#   queue: kubernetes

# steps:
# - label: ":white_check_mark: Successful Step"
#   command: "echo 'This step will pass successfully'"

# - label: ":x: Command Failure Only (Logic)"
#   command: "exit 2"

# - label: ":warning: Soft Fail (Does Not Block Pipeline)"
#   command: "exit 5"
#   soft_fail: true

# - label: ":rocket: Final Step (Always Runs)"
#   command: "echo 'Pipeline has completed!'"
steps:
- label: "Trigger Docker OOM"
  plugins:
  - docker#v5.12.0:
      image: "ubuntu:latest"
      memory: "256m" # Limit memory to 256MB
      memory_swap: "256m" # Prevent extra swap usage
      mount-buildkite-agent: false # Prevents Job API socket mount issues
  command: |
    echo "Disabling Buildkite Job API socket"
    export BUILDKITE_AGENT_JOB_API_SOCKET=/tmp/job-api.sock  # Override problematic socket path

    echo "Installing stress tool..."
    apt-get update && apt-get install -y stress

    echo "Attempting to consume more memory than allowed..."
    # This will exceed the 256MB limit and cause an OOM kill
    stress --vm 1 --vm-bytes 512M --timeout 10s

    echo "Finished stress command (if this runs, OOM didn't trigger)"
